<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>
body{font-family:DejaVu Sans,Arial,sans-serif;color:#111827;font-size:11px}.header{border-bottom:3px solid #1a7a4a;padding-bottom:14px;margin-bottom:18px}.school{font-size:24px;font-weight:800;color:#1a7a4a}.muted{color:#6b7280}.cards{width:100%;border-collapse:separate;border-spacing:8px;margin:12px 0 18px}.card{border:1px solid #d1d5db;padding:12px}.label{font-size:10px;color:#6b7280;text-transform:uppercase}.value{font-size:18px;font-weight:800;margin-top:4px}.green{color:#1a7a4a}.red{color:#dc2626}.amber{color:#b45309}table.data{width:100%;border-collapse:collapse;margin-bottom:18px}table.data th{background:#1a7a4a;color:#fff;text-align:left;padding:8px}table.data td{border:1px solid #e5e7eb;padding:7px}.section-title{font-size:15px;font-weight:800;margin:14px 0 8px}.right{text-align:right}.footer{position:fixed;bottom:16px;left:0;right:0;text-align:center;color:#6b7280;font-size:10px}
</style></head><body>
<div class="header"><div class="school">XYZ School</div><div class="muted">Financial Summary Report | {{ $from }} to {{ $to }}</div></div>
<table class="cards"><tr>
    <td class="card"><div class="label">Total Income</div><div class="value green">INR {{ number_format($totals['income'], 2) }}</div></td>
    <td class="card"><div class="label">Total Expenses</div><div class="value red">INR {{ number_format($totals['expenses'], 2) }}</div></td>
    <td class="card"><div class="label">Total Payroll</div><div class="value amber">INR {{ number_format($totals['payroll'], 2) }}</div></td>
    <td class="card"><div class="label">Net Profit/Loss</div><div class="value {{ $totals['profit'] >= 0 ? 'green' : 'red' }}">INR {{ number_format($totals['profit'], 2) }}</div></td>
</tr></table>
<div class="section-title">Income Summary</div>
<table class="data"><tr><th>Receipt</th><th>Student</th><th>Fee Type</th><th class="right">Amount</th><th>Date</th></tr>@foreach($incomes as $income)<tr><td>{{ $income->receipt_number }}</td><td>{{ $income->student_name }}</td><td>{{ $income->fee_type }}</td><td class="right">{{ number_format($income->amount, 2) }}</td><td>{{ $income->payment_date->format('d M Y') }}</td></tr>@endforeach</table>
<div class="section-title">Expense Summary</div>
<table class="data"><tr><th>Title</th><th>Category</th><th class="right">Amount</th><th>Date</th></tr>@foreach($expenses as $expense)<tr><td>{{ $expense->expense_title }}</td><td>{{ $expense->category }}</td><td class="right">{{ number_format($expense->amount, 2) }}</td><td>{{ $expense->expense_date->format('d M Y') }}</td></tr>@endforeach</table>
<div class="section-title">Payroll Summary</div>
<table class="data"><tr><th>Employee</th><th class="right">Salary</th><th class="right">Bonus</th><th class="right">Deduction</th><th class="right">Net Salary</th><th>Date</th></tr>@foreach($payrolls as $payroll)<tr><td>{{ $payroll->employee_name }}</td><td class="right">{{ number_format($payroll->salary, 2) }}</td><td class="right">{{ number_format($payroll->bonus, 2) }}</td><td class="right">{{ number_format($payroll->deduction, 2) }}</td><td class="right">{{ number_format($payroll->net_salary, 2) }}</td><td>{{ $payroll->payroll_date->format('d M Y') }}</td></tr>@endforeach</table>
<div class="footer">Generated by SchoolERP Finance Module</div>
</body></html>
